//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arbeitszeiten.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arbeitszeiten.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;de-de&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;Änderungen Rechnungsverwalter&lt;/title&gt;
        ///    &lt;meta name=&quot;author&quot; content=&quot;aarhor&quot; charset=&quot;UTF-8&quot;&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        html {
        ///            scroll-behavior: smooth;
        ///        }
        ///
        ///        body {
        ///            font: small verdana, arial, sans-serif;
        ///            color: #000000;
        ///        }
        ///
        ///        div.bluehead {
        ///            text-align: center;
        ///            color: #bdc1c6;
        ///            background-color: #0000aa;
        ///            padding: 5 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Aenderungen {
            get {
                return ResourceManager.GetString("Aenderungen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CREATE TABLE Taetigkeiten (
        ///    _id INTEGER PRIMARY KEY AUTOINCREMENT,
        ///    Datum date,
        ///    Uhrzeit datetime,
        ///    Tätigkeit TEXT
        ///);
        ///
        ///CREATE TABLE &quot;Zeiten&quot; (
        ///    &quot;_id&quot; INTEGER,
        ///    &quot;Datum&quot; DATE,
        ///    &quot;Start&quot; DATETIME,
        ///    &quot;Ende&quot; DATETIME,
        ///    &quot;Differenz&quot; DOUBLE,
        ///    &quot;MehrMinder_Stunden&quot; DOUBLE,
        ///    &quot;Bemerkung&quot; TEXT DEFAULT NULL,
        ///    &quot;Metadaten&quot; TEXT DEFAULT NULL,
        ///    PRIMARY KEY(&quot;_id&quot; AUTOINCREMENT)
        ///);
        ///
        ///CREATE VIEW &apos;view_geordnet&apos; AS
        ///select
        ///    *
        ///from
        ///    &quot;Zeiten&quot;
        ///order by
        ///    Datum,
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Erstellen {
            get {
                return ResourceManager.GetString("Erstellen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
